### ISSUE TITLE
API register gives "An error has occurred" 

### ISSUE THREAD

**Issue by MrPineMan** [fewieden/MMM-soccer#4]
I'm unable to get the API anyhow the program seems great to get! 
Does anyone else have the same issue ?

**Comment by fewieden** [comment]
Since this is not related to the module itself I suggest to write the API Provider football-data.org an email that you are unable to create an account. Be aware that the maintainer is currently overseas, so it could take a while until you get a response. Until then you can use the module without an API key, which only leads to a longer updating periods (every 30 minutes).

**Comment by MrPineMan** [comment]
Owh, so if i understand your awnser correctly. I can use the module with a refresh every 30min. 
But with using an API it only refesh faster... 
In that case ill use it without API! 

Thanks for your quick reply and clear awnser.

**Comment by fewieden** [comment]
Yes exactly. With API Key every 5 mins, without every 30 mins. This is only interesting for updates while matches are live ;)
